/* Generated by scripts/gen-typert.mjs — do not edit. */
import { z } from 'zod';
const req_fsList = z.object({ root: z.string(), path: z.string(), showHidden: z.boolean().optional() });
const res_fsList = z.union([z.object({ ok: z.literal(true), value: z.object({ entries: z.array(z.object({ name: z.string(), isDirectory: z.boolean(), size: z.number() })) }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_fsRead = z.object({ root: z.string(), path: z.string() });
const res_fsRead = z.union([z.object({ ok: z.literal(true), value: z.object({ content: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_fsWrite = z.object({ root: z.string(), path: z.string(), content: z.string() });
const res_fsWrite = z.union([z.object({ ok: z.literal(true), value: z.object({ path: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_fsCreateFile = z.object({ root: z.string(), path: z.string() });
const res_fsCreateFile = z.union([z.object({ ok: z.literal(true), value: z.object({ path: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_fsCreateDir = z.object({ root: z.string(), path: z.string() });
const res_fsCreateDir = z.union([z.object({ ok: z.literal(true), value: z.object({ path: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_fsRename = z.object({ root: z.string(), path: z.string(), newName: z.string() });
const res_fsRename = z.union([z.object({ ok: z.literal(true), value: z.object({ path: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_fsDelete = z.object({ root: z.string(), path: z.string() });
const res_fsDelete = z.union([z.object({ ok: z.literal(true), value: z.object({ path: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_gitStatus = z.object({ root: z.string(), repoPath: z.string() });
const res_gitStatus = z.union([z.object({ ok: z.literal(true), value: z.object({ branch: z.string(), dirtyCount: z.number(), changes: z.array(z.object({ path: z.string(), status: z.union([z.literal("M"), z.literal("A"), z.literal("D"), z.literal("U")]) })) }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_gitCheckout = z.object({ root: z.string(), repoPath: z.string(), branch: z.string() });
const res_gitCheckout = z.union([z.object({ ok: z.literal(true), value: z.object({ output: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_gitCreateBranch = z.object({ root: z.string(), repoPath: z.string(), name: z.string() });
const res_gitCreateBranch = z.union([z.object({ ok: z.literal(true), value: z.object({ output: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_gitPull = z.object({ root: z.string(), repoPath: z.string() });
const res_gitPull = z.union([z.object({ ok: z.literal(true), value: z.object({ output: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_chat = z.object({ messages: z.array(z.object({ role: z.union([z.literal("system"), z.literal("user"), z.literal("assistant")]), content: z.string() })), model: z.string(), apiBase: z.string(), apiKey: z.string() });
const res_chat = z.union([z.object({ ok: z.literal(true), value: z.object({ content: z.string() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_qqList = z.object({});
const res_qqList = z.union([z.object({ ok: z.literal(true), value: z.object({ sessions: z.array(z.object({ key: z.string(), peerId: z.string(), kind: z.union([z.literal("group"), z.literal("c2c")]), messages: z.array(z.object({ role: z.union([z.literal("user"), z.literal("assistant")]), content: z.string() })), updatedAt: z.number() })) }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_qqRead = z.object({ key: z.string() });
const res_qqRead = z.union([z.object({ ok: z.literal(true), value: z.object({ session: z.unknown().optional() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
const req_qqSend = z.object({ key: z.string(), content: z.string() });
const res_qqSend = z.union([z.object({ ok: z.literal(true), value: z.object({ ok: z.boolean() }) }), z.object({ ok: z.literal(false), error: z.object({ code: z.string(), message: z.string() }) })]);
export const TYPERT_REMOTE = {
    package: 'dsh-shiningweb-ui',
    descriptors: [
        {
            id: 'dsh-shiningweb-ui#shining/fsList',
            service: 'shining',
            namespace: 'shining',
            method: 'fsList',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsListRequest', schema: req_fsList } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsListResult', schema: res_fsList },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/fsRead',
            service: 'shining',
            namespace: 'shining',
            method: 'fsRead',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsReadRequest', schema: req_fsRead } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsReadResult', schema: res_fsRead },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/fsWrite',
            service: 'shining',
            namespace: 'shining',
            method: 'fsWrite',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsWriteRequest', schema: req_fsWrite } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsWriteResult', schema: res_fsWrite },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/fsCreateFile',
            service: 'shining',
            namespace: 'shining',
            method: 'fsCreateFile',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsCreateFileRequest', schema: req_fsCreateFile } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsCreateFileResult', schema: res_fsCreateFile },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/fsCreateDir',
            service: 'shining',
            namespace: 'shining',
            method: 'fsCreateDir',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsCreateDirRequest', schema: req_fsCreateDir } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsCreateDirResult', schema: res_fsCreateDir },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/fsRename',
            service: 'shining',
            namespace: 'shining',
            method: 'fsRename',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsRenameRequest', schema: req_fsRename } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsRenameResult', schema: res_fsRename },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/fsDelete',
            service: 'shining',
            namespace: 'shining',
            method: 'fsDelete',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#fsDeleteRequest', schema: req_fsDelete } },
            ],
            result: { mode: 'strict', typeSymbol: '#fsDeleteResult', schema: res_fsDelete },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/gitStatus',
            service: 'shining',
            namespace: 'shining',
            method: 'gitStatus',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#gitStatusRequest', schema: req_gitStatus } },
            ],
            result: { mode: 'strict', typeSymbol: '#gitStatusResult', schema: res_gitStatus },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/gitCheckout',
            service: 'shining',
            namespace: 'shining',
            method: 'gitCheckout',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#gitCheckoutRequest', schema: req_gitCheckout } },
            ],
            result: { mode: 'strict', typeSymbol: '#gitCheckoutResult', schema: res_gitCheckout },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/gitCreateBranch',
            service: 'shining',
            namespace: 'shining',
            method: 'gitCreateBranch',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#gitCreateBranchRequest', schema: req_gitCreateBranch } },
            ],
            result: { mode: 'strict', typeSymbol: '#gitCreateBranchResult', schema: res_gitCreateBranch },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/gitPull',
            service: 'shining',
            namespace: 'shining',
            method: 'gitPull',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#gitPullRequest', schema: req_gitPull } },
            ],
            result: { mode: 'strict', typeSymbol: '#gitPullResult', schema: res_gitPull },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/chat',
            service: 'shining',
            namespace: 'shining',
            method: 'chat',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#chatRequest', schema: req_chat } },
            ],
            result: { mode: 'strict', typeSymbol: '#chatResult', schema: res_chat },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/qqList',
            service: 'shining',
            namespace: 'shining',
            method: 'qqList',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#qqListRequest', schema: req_qqList } },
            ],
            result: { mode: 'strict', typeSymbol: '#qqListResult', schema: res_qqList },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/qqRead',
            service: 'shining',
            namespace: 'shining',
            method: 'qqRead',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#qqReadRequest', schema: req_qqRead } },
            ],
            result: { mode: 'strict', typeSymbol: '#qqReadResult', schema: res_qqRead },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        },
        {
            id: 'dsh-shiningweb-ui#shining/qqSend',
            service: 'shining',
            namespace: 'shining',
            method: 'qqSend',
            invocation: { kind: 'direct' },
            parameters: [
                { name: 'request', wire: 'request', source: 'json', codec: { mode: 'strict', typeSymbol: '#qqSendRequest', schema: req_qqSend } },
            ],
            result: { mode: 'strict', typeSymbol: '#qqSendResult', schema: res_qqSend },
            sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
        }
    ],
};
export default TYPERT_REMOTE;
