/**
 * 生成 typert 制品：从 typert-defs.mjs 单一数据源产出
 *   - src/client/remote.ts   （client 挂载的 TYPERT_REMOTE，strict zod codec）
 *   - lib/typert.host.js/.d.ts （host `./typert` 制品，typert-loader 自动注册）
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { methods, NAMESPACE, PACKAGE } from './typert-defs.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// 为每个 method 生成 schema const 声明（请求 + 结果）
function schemaConsts() {
  return methods
    .map((m) => `const req_${m.method} = ${m.request}\nconst res_${m.method} = ${m.result}`)
    .join('\n')
}

// 单个 method 的 descriptor 源码（parameters 单一 `request` wire 参数）
function descriptorOf(m) {
  return `    {
      id: '${PACKAGE}#${NAMESPACE}/${m.method}',
      service: '${NAMESPACE}',
      namespace: '${NAMESPACE}',
      method: '${m.method}',
      invocation: { kind: 'direct' as const },
      parameters: [
        { name: 'request', wire: 'request', source: 'json' as const, codec: { mode: 'strict' as const, typeSymbol: '#${m.method}Request', schema: req_${m.method} } },
      ],
      result: { mode: 'strict' as const, typeSymbol: '#${m.method}Result', schema: res_${m.method} },
      sourceLocation: { file: 'src/gateway.ts', line: 1, column: 1 },
    }`
}

const descriptors = methods.map(descriptorOf).join(',\n')

// 1) src/client/remote.ts
const clientSource = `/* Generated by scripts/gen-typert.mjs — do not edit. */
import { z } from 'zod'

${schemaConsts()}

export const TYPERT_REMOTE = {
  package: '${PACKAGE}',
  descriptors: [
${descriptors}
  ],
}
export default TYPERT_REMOTE
`

// 2) lib/typert.host.js
const hostSource = `/* Generated by scripts/gen-typert.mjs — do not edit. */
import { z } from 'zod'

${schemaConsts()}

export const TYPERT = {
  package: '${PACKAGE}',
  face: 'host',
  schemas: [],
  invocations: [
${descriptors}
  ],
  model: { services: [], events: [], objects: [] },
}
`

mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'src/client/remote.ts'), clientSource)
writeFileSync(join(root, 'lib/typert.host.js'), hostSource)
writeFileSync(join(root, 'lib/typert.host.d.ts'), '/* Generated — do not edit. */\nexport declare const TYPERT: unknown\n')
console.log('gen-typert: wrote src/client/remote.ts, lib/typert.host.{js,d.ts}')
